/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Alvorada Dynamic Design System
        'surface': '#001135',
        'surface-dim': '#001135',
        'surface-bright': '#29385d',
        'surface-container-lowest': '#000c2b',
        'surface-container-low': '#081a3d',
        'surface-container': '#0d1e42',
        'surface-container-high': '#19294d',
        'surface-container-highest': '#243458',
        'surface-variant': '#243458',
        'on-surface': '#d9e2ff',
        'on-surface-variant': '#c6c6cf',
        'inverse-surface': '#d9e2ff',
        'inverse-on-surface': '#202f54',
        'outline': '#8f9099',
        'outline-variant': '#45464e',
        'surface-tint': '#b9c5f2',
        // Primary (Azul Marinho do Clube)
        'primary': '#b9c5f2',
        'on-primary': '#222f53',
        'primary-container': '#0d1b3e',
        'on-primary-container': '#7784ad',
        'inverse-primary': '#515d84',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b9c5f2',
        'on-primary-fixed': '#0b1a3d',
        'on-primary-fixed-variant': '#39456b',
        // Secondary (Vermelho do Clube)
        'secondary': '#ffb3ae',
        'on-secondary': '#68000c',
        'secondary-container': '#9b0217',
        'on-secondary-container': '#ffa39d',
        'secondary-fixed': '#ffdad7',
        'secondary-fixed-dim': '#ffb3ae',
        'on-secondary-fixed': '#410004',
        'on-secondary-fixed-variant': '#930015',
        // Tertiary
        'tertiary': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#1b1d1d',
        'on-tertiary-container': '#848585',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        // Error
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Background
        'background': '#001135',
        'on-background': '#d9e2ff',
      },
      fontFamily: {
        sans: ['Lexend', 'system-ui', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'stat-lg': ['40px', { lineHeight: '1.0', fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        margin: '24px',
      },
    },
  },
  plugins: [],
};
