/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme]'],
  theme: {
    extend: {
      colors: {
        // CaixaFacil Design System — mapeados aos CSS vars dos temas
        'cf-bg': 'var(--cf-bg)',
        'cf-surface': 'var(--cf-surface)',
        'cf-surface-high': 'var(--cf-surface-high)',
        'cf-surface-highest': 'var(--cf-surface-highest)',
        'cf-border': 'var(--cf-border)',
        'cf-border-strong': 'var(--cf-border-strong)',
        'cf-text': 'var(--cf-text)',
        'cf-muted': 'var(--cf-muted)',
        'cf-muted-light': 'var(--cf-muted-light)',
        'cf-accent': 'var(--cf-accent)',
        'cf-accent-dim': 'var(--cf-accent-dim)',
        'cf-accent-glow': 'var(--cf-accent-glow)',
        'cf-accent-text': 'var(--cf-accent-text)',
        'cf-green': 'var(--cf-green)',
        'cf-red': 'var(--cf-red)',
        'cf-yellow': 'var(--cf-yellow)',
        'cf-blue': 'var(--cf-blue)',

        // Landing Page tokens (não mudam com o tema — são da LP estática)
        'lp-bg': '#0a0a0a',
        'lp-amber': '#d4a853',
        'lp-text': '#f5f0eb',
        'lp-muted': '#7a7060',
        'lp-border': 'rgba(255,255,255,0.08)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        lexend: ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1.4' }],
        'sm': ['0.8125rem', { lineHeight: '1.4' }],
        'base': ['0.9375rem', { lineHeight: '1.5' }],
        'lg': ['1.0625rem', { lineHeight: '1.5' }],
        'xl': ['1.25rem', { lineHeight: '1.3' }],
        '2xl': ['1.5rem', { lineHeight: '1.25' }],
        '3xl': ['2rem', { lineHeight: '1.2' }],
        '4xl': ['2.5rem', { lineHeight: '1.1' }],

        // Legacy aliases (para compatibilidade com páginas existentes)
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'stat-lg': ['40px', { lineHeight: '1.0', fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm: '4px',
        md: '10px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        margin: '24px',
      },
      boxShadow: {
        'cf': 'var(--cf-shadow)',
        'cf-sm': 'var(--cf-shadow-sm)',
        'cf-lg': 'var(--cf-shadow-lg)',
        'cf-accent': 'var(--cf-shadow-accent)',
      },
    },
  },
  plugins: [],
};
